version: '3'
services:
  api:
    build:
      context: ./api/prophecia
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Mapear el puerto del contenedor al puerto del host
    depends_on:
      - mongodb  # Dependencia de MongoDB

  ui:
    build:
      context: ./ui/prophecia-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Mapear el puerto del contenedor al puerto del host

  mongodb:
    image: mongo
    ports:
      - "3100:27017"  # Mapear el puerto del contenedor al puerto del host
